version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
      PG_DATA: /data/postgres
    volumes:
      - tododb:/data/postgres
  express:
    build: .
    ports:
      - 3000:3000
    environment:
       DB_USER: admin
       DB_PASSWORD: password
       DB_HOST: db
       DB_NAME: tododb
    depends_on:
      - db


volumes:
  tododb:
  ecomm-pgadmin:


